### ISSUE TITLE
Generate OpenSSH Keys

### ISSUE THREAD

**Issue by genedna** [coreos/openssh-keys#12]
Now, the *openssh-keys* could parse SSH keys, I want to add generate keys and save to files functions.

Support types:

- [x] ssh-rsa 1024/2048/4096
- [ ] ssh-dss
- [ ] ssh-ed25519
- [ ] ecdsa-ssh2-nistp256
- [ ] ecdsa-ssh2-nistp384
- [ ] ecdsa-ssh2-nistp521

**Comment by sdemos** [comment]
In order to support useful generation of ssh keys, we would need to be able to speak the private key format, and then implement cryptographically secure key generation. In addition, the current implementations of ed25519 and the ecdsa curves would have to get smarter, they are currently only represented as opaque strings because I didn't know enough about how to validate points on an elliptic curve. 

I'm partial to leaving the generation to real crypto libraries. I fear that it expands the scope of this library too far. That is why I included the functions for constructing rsa and dss keys from their component parts. I'm not strictly opposed to including private key representations and ssh key generation, but I would want us to be very confident in any implementation if I were to include it. 

A possible option would be to include documentation for generating keys with existing libraries and then constructing the public key here. We could also improve the ed25519 and ecdsa curve implementations to allow for arbitrary construction.

**Comment by genedna** [comment]
I just found my codes which generating `ssh-rsa` code couldn't run in the _**Windows**_ platform, because I use the [openssl-sys](https://github.com/sfackler/rust-openssl/tree/master/openssl-sys) . Now, I am looking for other _**pure**_ library to generate.
